name: CI/CD with terraform
on:
  push: 
    branches:
      - Complete-CI/CD-with-Terraform-Aws


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME:  ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_PUBLIC_KEY }}
  AWS_REGION: eu-north-1

  jobs: 
    deploy-infras:
      runs-on: ubuntu-latest
      stages:
        - name: Checkout
          users actions/Checkout@v2
        - name: setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_wrapper: false
        - name: Terraform init
          id: init
          run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=eu-north-1"
          working-directory: ./terraform
        - name: Terraform plan
          id: plan
          runs: |-
            terraform plan \
            -var="region=eu-north-1" \
            -var="public_key=$PUBLIC_SSH_KEY" \
            -var="private_key=$PRIVATE_SSH_KEY" \
            -var="key_name=deployer-key" \
            -out=PLAN
          working-directory: ./terraform
        - name: Terraform Apply
          id: Apply
          run: terraform apply PLAN
          working-directory: ./terraform







          



















